### ISSUE TITLE
Dabatase handler refacto

### ISSUE THREAD

**Issue by BenoitSafari** [Cinevoraces/cinevoraces#169]
We need to rework and simplify api/database interactions. API should be the only source of truth concerning the database, as such we need to setup a migration strategy within the DB. Some queries uses the reduceSelect/reduceWhere functions, it should be based on the controller schema.

## Tasks
- [x] **Set a data migration strategy** https://github.com/Cinevoraces/cinevoraces/pull/180
- [x] **Create a Repository class that interface database interactions** https://github.com/Cinevoraces/cinevoraces/pull/179
- [x] **~~Create current DB views and functions in the API services~~** _Canceled_
- [x] **Create a QueryString class that handles the front-client queries instead of DB related functions** https://github.com/Cinevoraces/cinevoraces/pull/179
