### ISSUE TITLE
User credentials manage (email service)

### ISSUE THREAD

**Issue by BenoitSafari** [Cinevoraces/cinevoraces#172]
## Tasks
- [ ] **Request Limit on Endpoints**
  We need to implement a request limit on our API endpoints to prevent abuse. This includes: 
     - A maximum limit on every requests. 
     - A maximum limit of 3 requests on sensitive endpoints (reset password/login)

- [ ] **Create a email sender class**
  This class is needed to sends mails in the following cases:
    - Password reset request
    - Email confirmation on registering

- [ ] **Add the reset password function to the APP/API**

#### Sources
- https://github.com/fastify/fastify-rate-limit
- https://developers.brevo.com/docs/getting-started
- https://nodemailer.com/
